### PR TITLE
made it faster a couple of times

### PR DESCRIPTION
**Pull request by streamich**
Wrote it such that it does not use `.slice()` on every step, this way it is 2-3x faster, given how popular this package is on NPM.

### CODE REVIEW

**Comment by streamich** [comment]
I don't think the Travis build fails because of my PR.

**Comment by darsain** [comment]
Yeah there is some npm issue on travis for older node version it seems.

Looks good, but can you remove the `package-lock.json`?

**Comment by streamich** [comment]
Removed `package-lock.json`

**Comment by darsain** [comment]
Thank you. Published as 1.1.0.

**Pull request merged**
